name: INPE CI (light)

on:
  pull_request:
  push:
    branches: [ inpe/main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Lint wrappers and selected scripts
        run: |
          shopt -s globstar || true
          shellcheck -S style tools/obsproc-wrapper/scripts/**/*.sh || true
          shellcheck -S warning scripts/*.sh || true

  tree-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure wrapper expected files exist
        run: |
          test -f docs/INPE-DELTA.md
          test -f tools/obsproc-wrapper/scripts/run_dump_gdas_local.sh
          test -f tools/obsproc-wrapper/configs/groups.conf
